using older version of mac os

diff --git a/.github/workflows/basic.yml b/.github/workflows/basic.yml
--- a/.github/workflows/basic.yml
+++ b/.github/workflows/basic.yml
@@ -16,12 +16,7 @@ jobs:
   build:
     strategy:
       matrix:
-        os: [ubuntu-20.04, ubuntu-22.04]
-        include:
-          - os: macOS-11
-            openssl-version: 3
-          - os: macOS-11
-            openssl-version: 1.1
+        os: [ubuntu-20.04, ubuntu-22.04, macOS-10.15, macOS-11]
 
     runs-on: ${{ matrix.os }}
 
@@ -46,27 +41,18 @@ jobs:
       run: |
         brew list cmake &>/dev/null || brew install cmake
         brew list lcov &>/dev/null || brew install lcov
-        brew uninstall --ignore-dependencies openssl
-        brew install openssl@${{matrix.openssl-version}}
-        find /usr/local -name "libcrypto*dylib"
+        brew list openssl &>/dev/null || brew install openssl
+        echo "list ossl folders"
+        ls -l /usr/local/opt/*
+        ls -l /usr/local/opt/openssl/lib/*
+        echo "done"
         mkdir $CMAKE_BUILD_DIR
 
     - name: Build
       shell: bash
       working-directory: ${{env.CMAKE_BUILD_DIR}}
       run: |
-        export OPENSSL_VERSION=${{matrix.openssl-version}}
-        if [[ !  -z  ${OPENSSL_VERSION} ]]; then
-          echo "*** OPENSSL_VERSION found"
-          echo "*** inside openssl"
-          ls -l /usr/local/opt/openssl*
-          echo "*** inside openssl lib folder"
-          ls -l /usr/local/opt/openssl/lib/
-          cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DBUILD_TESTS=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@${OPENSSL_VERSION} $GITHUB_WORKSPACE
-        else
-          echo "*** OPENSSL_VERSION NOT found"
         cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DBUILD_TESTS=ON $GITHUB_WORKSPACE
-        fi
         make -j4
         make test
 
@@ -78,23 +64,15 @@ jobs:
         echo "*** Azurite version = $(azurite --version)"
         azurite --silent --loose --location $CMAKE_BUILD_DIR/azurite &
         
-    - name: Test with Azurite
+    - name: Test
       shell: bash
       working-directory: ${{env.CMAKE_BUILD_DIR}}
       run: |
          # Create container called test as TileDB expects the container to be already created
-         az && echo "Azure CLI installed!"
+         az && echo "Azure CLI installed!" || echo "Azure CLI not FOUND"
          az storage container create -n test --connection-string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;"
          ./azure-storage-test [blob]
-
-    - name: Test
-      shell: bash
-      working-directory: ${{env.CMAKE_BUILD_DIR}}
-      run: ./azure-storage-test
-      env:
-        TEST_CONNECTION_STRING: ${{ secrets.TEST_CONNECTION_STRING }}
-        TEST_ADLS_CONNECTION_STRING: ${{ secrets.TEST_ADLS_CONNECTION_STRING }}
-
+        
     - name: Upload Coverage to CodeCov
       uses: codecov/codecov-action@v3
       with:
